
select * from churntable
-- Q1. What is the total revenue generated by male vs. female customers?
SELECT Gender,
       SUM(`Purchase Amount (USD)`) AS revenue
FROM churntable
GROUP BY Gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT `Customer ID`,
       `Purchase Amount (USD)`
FROM churntable
WHERE `Discount Applied` = 'Yes'
  AND `Purchase Amount (USD)` >= (
      SELECT AVG(`Purchase Amount (USD)`)
      FROM churntable
  );

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT `Item Purchased`,
       ROUND(AVG(`Review Rating`), 2) AS `Average Product Rating`
FROM churntable
GROUP BY `Item Purchased`
ORDER BY AVG(`Review Rating`) DESC
LIMIT 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT `Shipping Type`,
       ROUND(AVG(`Purchase Amount (USD)`), 2) AS `Average Purchase Amount`
FROM churntable
WHERE `Shipping Type` IN ('Standard', 'Express')
GROUP BY `Shipping Type`;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-su
SELECT `Subscription Status`,
       COUNT(`Customer ID`) AS total_customers,
       ROUND(AVG(`Purchase Amount (USD)`), 2) AS avg_spend,
       ROUND(SUM(`Purchase Amount (USD)`), 2) AS total_revenue
FROM churntable
GROUP BY `Subscription Status`
ORDER BY total_revenue DESC, avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
SELECT `Item Purchased`,
       ROUND(100 * SUM(CASE
                        WHEN `Discount Applied` = 'Yes' THEN 1
                        ELSE 0
                     END) / COUNT(*),
           2
       ) AS discount_rate
FROM churntable
GROUP BY `Item Purchased`
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total --number of previous purchases, and show the count of each segment. with customer_type as (
SELECT `Customer ID`,
       `Previous Purchases`,
       CASE
           WHEN `Previous Purchases` = 1 THEN 'New'
           WHEN `Previous Purchases` BETWEEN 2 AND 10 THEN 'Returning'
           ELSE 'Loyal'
       END AS customer_segment
FROM churntable;
SELECT customer_segment,
       COUNT(*) AS `Number of Customers`
FROM customer_type
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT
        `Category`,
        `Item Purchased`,
        COUNT(`Customer ID`) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY `Category`
            ORDER BY COUNT(`Customer ID`) DESC
        ) AS item_rank
    FROM churntable
    GROUP BY `Category`, `Item Purchased`
)

SELECT
    item_rank,
    `Category`,
    `Item Purchased`,
    total_orders
FROM item_counts
WHERE item_rank<=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe? select subscription_status,
SELECT `Subscription Status`,
       COUNT(`Customer ID`) AS `Repeat Buyers`
FROM churntable
WHERE `Previous Purchases` > 5
GROUP BY `Subscription Status`;
 
 -- Q10. What is the revenue contribution of each age group?
SELECT
    CASE
        WHEN Age BETWEEN 0 AND 4 THEN '0-4'
        WHEN Age BETWEEN 5 AND 12 THEN '5-12'
        WHEN Age BETWEEN 13 AND 20 THEN '13-20'
        WHEN Age BETWEEN 21 AND 35 THEN '21-35'
        WHEN Age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '50+'
    END AS age_group,
    SUM(`Purchase Amount (USD)`) AS total_revenue
FROM churntable
GROUP BY age_group
ORDER BY total_revenue DESC;
